export const SET_ALERT = 'SET_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SET_LOGIN = 'SET_LOGIN'
export const SET_USERTYPE = 'SET_USERTYPE'
export const SET_USER_INITIAL = 'SET_USER_INITIAL'
export const CLEAR_LOGIN = 'CLEAR_LOGIN'
export const SET_DIVISIONS = 'SET_DIVISIONS'
export const SET_AREAS = 'SET_AREAS'
export const SET_ACTIVE_DIVISION = 'SET_ACTIVE_DIVISION'
export const SET_ACTIVE_AREA = 'SET_ACTIVE_AREA'
export const SET_CURRENT_DIVISION = 'SET_CURRENT_DIVISION'
export const SET_CURRENT_AREA = 'SET_CURRENT_AREA'
export const CLEAR_AUTH_DEFAULTS = 'CLEAR_AUTH_DEFAULTS'

export const SET_CREATE_ID = 'SET_CREATE_ID'
export const SET_UPDATE_ID = 'SET_UPDATE_ID'
export const CLEAR_TABLE_ID = 'CLEAR_TABLE_ID'
export const RELOAD_TABLE = 'RELOAD_TABLE'


export const SET_CLIENT_TABLE_STATUS = 'SET_CLIENT_TABLE_STATUS'
export const SET_CLIENT_TABLE_ID = 'SET_CLIENT_TABLE_ID'
export const CLEAR_CLIENT_TABLE_ID = 'CLEAR_CLIENT_TABLE_ID'
export const SET_CLIENT_TABLE_TYPE = 'SET_CLIENT_TABLE_TYPE'
export const CLEAR_CLIENT_TABLE_TYPE = 'CLEAR_CLIENT_TABLE_TYPE'
export const CLIENT_UPDATE_ID = 'CLIENT_UPDATE_ID'
export const CLIENT_INIT_TABLE_ACTIVE = 'CLIENT_INIT_TABLE_ACTIVE'
export const CLIENT_TABLE_REFRESH = 'CLIENT_TABLE_REFRESH'

export const SET_CLIENT_LINE_STATUS = 'SET_CLIENT_LINE_STATUS'
export const SET_CLIENT_LINE_ID = 'SET_CLIENT_LINE_ID'
export const CLEAR_CLIENT_LINE_ID = 'CLEAR_CLIENT_LINE_ID'
export const SET_CLIENT_LINE_TYPE = 'SET_CLIENT_LINE_TYPE'
export const CLEAR_CLIENT_LINE_TYPE = 'CLEAR_CLIENT_LINE_TYPE'
export const CLIENT_LINE_UPDATE_ID = 'CLIENT_LINE_UPDATE_ID'
export const CLIENT_INIT_LINE_ACTIVE = 'CLIENT_INIT_LINE_ACTIVE'
export const CLIENT_LINE_REFRESH = 'CLIENT_LINE_REFRESH'


export const CHANGE_ROLE = 'CHANGE_ROLE'

// FOR DYNAMIC UPDATEING OF VUE-TABLES-2 V-CLIENT-TABLE
export const UPDATE_CLIENTTABLE = 'UPDATE_CLIENTTABLE'
export const CLEAR_CLIENTTABLE = 'CLEAR_CLIENTTABLE'
